name: Release Management

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
      prerelease:
        description: 'Create as prerelease'
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci

      - name: Bump version
        id: version
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update CHANGELOG
        run: |
          cat > CHANGELOG_ENTRY.md << EOF
          ## v${{ steps.version.outputs.version }} - $(date +%Y-%m-%d)
          
          ### Added
          - New features and improvements
          
          ### Changed
          - Updates and modifications
          
          ### Fixed
          - Bug fixes and corrections
          
          EOF
          
          if [ -f CHANGELOG.md ]; then
            cat CHANGELOG.md >> CHANGELOG_ENTRY.md
            mv CHANGELOG_ENTRY.md CHANGELOG.md
          else
            mv CHANGELOG_ENTRY.md CHANGELOG.md
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: release v${{ steps.version.outputs.version }}"
          title: "Release v${{ steps.version.outputs.version }}"
          body: |
            ## Release v${{ steps.version.outputs.version }}
            
            This PR bumps the version to v${{ steps.version.outputs.version }} and updates the changelog.
            
            ### Checklist
            - [ ] Version bump is correct
            - [ ] CHANGELOG.md is updated
            - [ ] All tests pass
            - [ ] Ready to publish to npm
          branch: release/v${{ steps.version.outputs.version }}
          labels: release, automated